# https://jupyterbook.org/customize/config.html

title                       : Perl 5 By Example
author                      : David Medinets
copyright                   : "2020"
logo                        : logo.jpg
home_page_in_navbar         : false
